name: owo
description: API Wrapper for https://whats-th.is/
version: 1.0.6
homepage: https://owo.codes/source/owo.dart

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.12.1
  meta: ^1.1.8
  dartz: ^0.9.0
  yaml: ^2.2.1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  import_sorter: ^2.0.1
